version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 20
    versioning-strategy: increase
    directories:
      - "/"
      - "__tests__/test-react-project"
      - "__tests__/test-nextjs-project"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      development-dependencies:
        dependency-type: development
        patterns:
          - "*"
      production-dependencies:
        dependency-type: production
        patterns:
          - "*"

  - package-ecosystem: github-actions
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "devcontainers"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
